version: '2'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DESTINATION_PROJECT_URL
      - KBC_DESTINATION_PROJECT_TOKEN
      - KBC_SOURCE_PROJECT_URL
      - KBC_SOURCE_PROJECT_TOKEN
